# Development of private prison longitude and latitude data scraping

In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
from src.data import private_prison_locations

In [5]:
df = private_prison_locations.load_data()
df

       prison_name provider postal_code
0        Altcourse   Sodexo      L9 7LH
1         Ashfield    Serco    BS16 9QJ
2      Bronzefield   Sodexo    TW15 3JZ
3        Doncaster    Serco     DN5 8UX
4         Dovegate    Serco    ST14 8XR
5       Five Wells      G4S     NN8 2NH
6      Forest Bank   Sodexo     M27 8FB
7        Fosse Way    Serco    LE18 4TN
8   Northumberland   Sodexo    NE65 9XG
9          Oakwood      G4S    WV10 7QD
10            Parc      G4S    CF35 6AP
11    Peterborough   Sodexo     PE3 7PD
12        Rye Hill      G4S    CV23 8SZ
13       Thameside    Serco    SE28 0FJ

In [51]:
postal_codes = private_prison_locations.get_postal_code(df)
postal_codes

['L9+7LH',
 'BS16+9QJ',
 'TW15+3JZ',
 'DN5+8UX',
 'ST14+8XR',
 'NN8+2NH',
 'M27+8FB',
 'LE18+4TN',
 'NE65+9XG',
 'WV10+7QD',
 'CF35+6AP',
 'PE3+7PD',
 'CV23+8SZ',
 'SE28+0FJ']

In [52]:
postal_codes[0]

'L9+7LH'

In [73]:
endpoint = "https://api.getthedata.com/postcode/"
private_prison_locations.download_data(endpoint, postal_codes)

[{'postcode': 'L9 7LH', 'latitude': '53.460927', 'longitude': '-2.936031'},
 {'postcode': 'BS16 9QJ', 'latitude': '51.482420', 'longitude': '-2.438869'},
 {'postcode': 'TW15 3JZ', 'latitude': '51.432921', 'longitude': '-0.482850'},
 {'postcode': 'DN5 8UX', 'latitude': '53.525178', 'longitude': '-1.145003'},
 {'postcode': 'ST14 8XR', 'latitude': '52.872046', 'longitude': '-1.783109'},
 {'postcode': 'NN8 2NH', 'latitude': '52.297422', 'longitude': '-0.697031'},
 {'postcode': 'M27 8FB', 'latitude': '53.514251', 'longitude': '-2.302093'},
 {'postcode': 'LE18 4TN', 'latitude': '52.582480', 'longitude': '-1.143503'},
 {'postcode': 'NE65 9XG', 'latitude': '55.296086', 'longitude': '-1.635300'},
 {'postcode': 'WV10 7QD', 'latitude': '52.647955', 'longitude': '-2.113013'},
 {'postcode': 'CF35 6AP', 'latitude': '51.530946', 'longitude': '-3.563142'},
 {'postcode': 'PE3 7PD', 'latitude': '52.586514', 'longitude': '-0.259961'},
 {'postcode': 'CV23 8SZ', 'latitude': '52.327520', 'longitude': '-1.242801'},
 {'postcode': 'SE28 0FJ', 'latitude': '51.493450', 'longitude': '0.087506'}]

In [27]:
import requests

In [68]:
url = f"{endpoint}{postal_codes[0]}"
response = requests.get(url)
data = response.json()

In [72]:
data['data'].get('latitude')

'53.460927'

In [74]:
from src.data import private_prison_locations

In [79]:
private_prison_locations.main()

       prison_name provider postal_code   latitude  longitude
0        Altcourse   Sodexo      L9 7LH  53.460927  -2.936031
1         Ashfield    Serco    BS16 9QJ  51.482420  -2.438869
2      Bronzefield   Sodexo    TW15 3JZ  51.432921  -0.482850
3        Doncaster    Serco     DN5 8UX  53.525178  -1.145003
4         Dovegate    Serco    ST14 8XR  52.872046  -1.783109
5       Five Wells      G4S     NN8 2NH  52.297422  -0.697031
6      Forest Bank   Sodexo     M27 8FB  53.514251  -2.302093
7        Fosse Way    Serco    LE18 4TN  52.582480  -1.143503
8   Northumberland   Sodexo    NE65 9XG  55.296086  -1.635300
9          Oakwood      G4S    WV10 7QD  52.647955  -2.113013
10            Parc      G4S    CF35 6AP  51.530946  -3.563142
11    Peterborough   Sodexo     PE3 7PD  52.586514  -0.259961
12        Rye Hill      G4S    CV23 8SZ  52.327520  -1.242801
13       Thameside    Serco    SE28 0FJ  51.493450   0.087506