# Development and testing for prison performance visualization

## Script test

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.visualization.state_of_our_prisons import plotly_prison_performance

In [3]:
df = plotly_prison_performance.test_data()
df

      year  outstanding  good  concern  serious_concern
0  2015–16            7    67       21                5
1  2016–17            8    50       34                8
2  2017–18           12    42       33               13
3  2018–19           13    50       24               14
4  2019–20           16    55       24                6
5  2022–23           11    52       30                8
6  2023-24           11    47       29               13

In [4]:
df.melt(id_vars=['year'], value_vars=['outstanding', 'good', 'concern', 'serious_concern'], var_name='number')

       year           number  value
0   2015–16      outstanding      7
1   2016–17      outstanding      8
2   2017–18      outstanding     12
3   2018–19      outstanding     13
4   2019–20      outstanding     16
5   2022–23      outstanding     11
6   2023-24      outstanding     11
7   2015–16             good     67
8   2016–17             good     50
9   2017–18             good     42
10  2018–19             good     50
11  2019–20             good     55
12  2022–23             good     52
13  2023-24             good     47
14  2015–16          concern     21
15  2016–17          concern     34
16  2017–18          concern     33
17  2018–19          concern     24
18  2019–20          concern     24
19  2022–23          concern     30
20  2023-24          concern     29
21  2015–16  serious_concern      5
22  2016–17  serious_concern      8
23  2017–18  serious_concern     13
24  2018–19  serious_concern     14
25  2019–20  serious_concern      6
26  2022–23  serious_concern      8
27  2023-24  serious_concern     13

In [30]:
df = plotly_prison_performance.test_data()
df

       year           rating  number
0   2015–16  serious_concern       5
1   2016–17  serious_concern       8
2   2017–18  serious_concern      13
3   2018–19  serious_concern      14
4   2019–20  serious_concern       6
5   2022–23  serious_concern       8
6   2023-24  serious_concern      13
7   2015–16          concern      21
8   2016–17          concern      34
9   2017–18          concern      33
10  2018–19          concern      24
11  2019–20          concern      24
12  2022–23          concern      30
13  2023-24          concern      29
14  2015–16             good      67
15  2016–17             good      50
16  2017–18             good      42
17  2018–19             good      50
18  2019–20             good      55
19  2022–23             good      52
20  2023-24             good      47
21  2015–16      outstanding       7
22  2016–17      outstanding       8
23  2017–18      outstanding      12
24  2018–19      outstanding      13
25  2019–20      outstanding      16
26  2022–23      outstanding      11
27  2023-24      outstanding      11

In [17]:
import plotly.colors as colors

In [18]:
colors.qualitative.Prism

['rgb(95, 70, 144)',
 'rgb(29, 105, 150)',
 'rgb(56, 166, 165)',
 'rgb(15, 133, 84)',
 'rgb(115, 175, 72)',
 'rgb(237, 173, 8)',
 'rgb(225, 124, 5)',
 'rgb(204, 80, 62)',
 'rgb(148, 52, 110)',
 'rgb(111, 64, 112)',
 'rgb(102, 102, 102)']

In [35]:
plotly_prison_performance.generate_traces(df)

[Bar({
     'hovertemplate': '%{y}%',
     'marker': {'color': 'rgb(204, 80, 62)'},
     'name': 'serious_concern',
     'textangle': 0,
     'textposition': 'auto',
     'x': [2015–16, 2016–17, 2017–18, 2018–19, 2019–20, 2022–23, 2023-24],
     'y': [5, 8, 13, 14, 6, 8, 13]
 }),
 Bar({
     'hovertemplate': '%{y}%',
     'marker': {'color': 'rgb(237, 173, 8)'},
     'name': 'concern',
     'textangle': 0,
     'textposition': 'auto',
     'x': [2015–16, 2016–17, 2017–18, 2018–19, 2019–20, 2022–23, 2023-24],
     'y': [21, 34, 33, 24, 24, 30, 29]
 }),
 Bar({
     'hovertemplate': '%{y}%',
     'marker': {'color': 'rgb(115, 175, 72)'},
     'name': 'good',
     'textangle': 0,
     'textposition': 'auto',
     'x': [2015–16, 2016–17, 2017–18, 2018–19, 2019–20, 2022–23, 2023-24],
     'y': [67, 50, 42, 50, 55, 52, 47]
 }),
 Bar({
     'hovertemplate': '%{y}%',
     'marker': {'color': 'rgb(15, 133, 84)'},
     'name': 'outstanding',
     'textangle': 0,
     'textposition': 'auto',
     'x': [2015–16, 2016–17, 2017–18, 2018–19, 2019–20, 2022–23, 2023-24],
     'y': [7, 8, 12, 13, 16, 11, 11]
 })]

In [36]:
plotly_prison_performance.create_chart(df)

In [45]:
plotly_prison_performance.main()