# Development and testing for social characteristics visualization

## Script test

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.visualization.people_in_prison import plotly_social_characteristics

In [19]:
df = plotly_social_characteristics.test_data()
df

,characteristic,group,value,wrapped_characteristic
0,Taken into care as a child,prison_male,24.0,Taken into care as<br>a child
1,Experienced abuse as a child,prison_male,27.0,Experienced abuse<br>as a child
2,Observed violence in the home as a child,prison_male,40.0,Observed violence<br>in the home as a<br>child
3,Expelled or permanently excluded from school,prison_male,43.0,Expelled or<br>permanently<br>excluded from<br...
4,Unemployed in the four weeks before custody,prison_male,67.0,Unemployed in the<br>four weeks before<br>custody
5,Have children under the age of 18,prison_male,45.0,Have children<br>under the age of<br>18
6,Are young fathers (aged 18-20),prison_male,19.0,Are young fathers<br>(aged 18-20)
7,Have symptoms indicative of psychosis,prison_male,15.0,Have symptoms<br>indicative of<br>psychosis
8,Identified as suffering from both anxiety and ...,prison_male,23.0,Identified as<br>suffering from<br>both anxiet...
9,Have attempted suicide at some point,prison_male,21.0,Have attempted<br>suicide at some<br>point
10,Taken into care as a child,prison_female,31.0,Taken into care as<br>a child
11,Experienced abuse as a child,prison_female,53.0,Experienced abuse<br>as a child
12,Observed violence in the home as a child,prison_female,50.0,Observed violence<br>in the home as a<br>child
13,Expelled or permanently excluded from school,prison_female,32.0,Expelled or<br>permanently<br>excluded from<br...
14,Unemployed in the four weeks before custody,prison_female,81.0,Unemployed in the<br>four weeks before<br>custody
15,Have children under the age of 18,prison_female,47.0,Have children<br>under the age of<br>18
16,Have symptoms indicative of psychosis,prison_female,25.0,Have symptoms<br>indicative of<br>psychosis
17,Identified as suffering from both anxiety and ...,prison_female,49.0,Identified as<br>suffering from<br>both anxiet...
18,Have attempted suicide at some point,prison_female,46.0,Have attempted<br>suicide at some<br>point
19,Experienced abuse as a child,prison_all,29.0,Experienced abuse<br>as a child
20,Observed violence in the home as a child,prison_all,41.0,Observed violence<br>in the home as a<br>child
21,Regularly truant from school,prison_all,59.0,Regularly truant<br>from school
22,Expelled or permanently excluded from school,prison_all,42.0,Expelled or<br>permanently<br>excluded from<br...
23,No qualifications,prison_all,47.0,No qualifications
24,Unemployed in the four weeks before custody,prison_all,68.0,Unemployed in the<br>four weeks before<br>custody
25,Never had a job,prison_all,13.0,Never had a job
26,Homeless before entering custody,prison_all,15.0,Homeless before<br>entering custody
27,Have symptoms indicative of psychosis,prison_all,16.0,Have symptoms<br>indicative of<br>psychosis
28,Identified as suffering from both anxiety and ...,prison_all,25.0,Identified as<br>suffering from<br>both anxiet...
29,Have ever used Class A drug,prison_all,64.0,Have ever used<br>Class A drug
30,Drank alcohol every day in the four weeks befo...,prison_all,22.0,Drank alcohol<br>every day in the<br>four week...
31,Taken into care as a child,general_pop,2,Taken into care as<br>a child
32,Experienced abuse as a child,general_pop,20,Experienced abuse<br>as a child
33,Observed violence in the home as a child,general_pop,14,Observed violence<br>in the home as a<br>child
34,Regularly truant from school,general_pop,5,Regularly truant<br>from school
35,Expelled or permanently excluded from school,general_pop,<1,Expelled or<br>permanently<br>excluded from<br...
36,No qualifications,general_pop,15,No qualifications
37,Unemployed in the four weeks before custody,general_pop,7.7,Unemployed in the<br>four weeks before<br>custody
38,Never had a job,general_pop,3.9,Never had a job
39,Homeless before entering custody,general_pop,4,Homeless before<br>entering custody
40,Have children under the age of 18,general_pop,27,Have children<br>under the age of<br>18
41,Are young fathers (aged 18-20),general_pop,4,Are young fathers<br>(aged 18-20)
42,Have symptoms indicative of psychosis,general_pop,4,Have symptoms<br>indicative of<br>psychosis
43,Identified as suffering from both anxiety and ...,general_pop,15,Identified as<br>suffering from<br>both anxiet...
44,Have attempted suicide at some point,general_pop,6,Have attempted<br>suicide at some<br>point
45,Have ever used Class A drug,general_pop,13,Have ever used<br>Class A drug
46,Drank alcohol every day in the four weeks befo...,general_pop,16,Drank alcohol<br>every day in the<br>four week...

## Development

In [17]:
import plotly.graph_objects as go
import pandas as pd

In [20]:
df = plotly_social_characteristics.test_data()

In [24]:
traces = plotly_social_characteristics.generate_traces(df)
traces

[Scatter({
     'hovertemplate': '%{x}',
     'marker': {'color': '#EF553B'},
     'name': 'prison_male',
     'orientation': 'h',
     'text': [prison_male, prison_male, prison_male, prison_male, prison_male,
              prison_male, prison_male, prison_male, prison_male, prison_male],
     'textposition': 'top center',
     'texttemplate': '%{text}%',
     'x': [24.0, 27.0, 40.0, 43.0, 67.0, 45.0, 19.0, 15.0, 23.0, 21.0],
     'y': [Taken into care as<br>a child, Experienced abuse<br>as a child, Observed
           violence<br>in the home as a<br>child, Expelled
           or<br>permanently<br>excluded from<br>school, Unemployed in the<br>four
           weeks before<br>custody, Have children<br>under the age of<br>18, Are
           young fathers<br>(aged 18-20), Have symptoms<br>indicative
           of<br>psychosis, Identified as<br>suffering from<br>both anxiety
           and<br>depression, Have attempted<br>suicide at some<br>point]
 }),
 Scatter({
     'hovertemplate': '%{x}',
     'marker': {'color': '#636efa'},
     'name': 'prison_female',
     'orientation': 'h',
     'text': [prison_female, prison_female, prison_female, prison_female,
              prison_female, prison_female, prison_female, prison_female,
              prison_female],
     'textposition': 'top center',
     'texttemplate': '%{text}%',
     'x': [31.0, 53.0, 50.0, 32.0, 81.0, 47.0, 25.0, 49.0, 46.0],
     'y': [Taken into care as<br>a child, Experienced abuse<br>as a child, Observed
           violence<br>in the home as a<br>child, Expelled
           or<br>permanently<br>excluded from<br>school, Unemployed in the<br>four
           weeks before<br>custody, Have children<br>under the age of<br>18, Have
           symptoms<br>indicative of<br>psychosis, Identified as<br>suffering
           from<br>both anxiety and<br>depression, Have attempted<br>suicide at
           some<br>point]
 }),
 Scatter({
     'hovertemplate': '%{x}',
     'marker': {'color': '#ab63fa'},
     'name': 'prison_all',
     'orientation': 'h',
     'text': [prison_all, prison_all, prison_all, prison_all, prison_all,
              prison_all, prison_all, prison_all, prison_all, prison_all,
              prison_all, prison_all],
     'textposition': 'top center',
     'texttemplate': '%{text}%',
     'x': [29.0, 41.0, 59.0, 42.0, 47.0, 68.0, 13.0, 15.0, 16.0, 25.0, 64.0, 22.0],
     'y': [Experienced abuse<br>as a child, Observed violence<br>in the home as
           a<br>child, Regularly truant<br>from school, Expelled
           or<br>permanently<br>excluded from<br>school, No qualifications,
           Unemployed in the<br>four weeks before<br>custody, Never had a job,
           Homeless before<br>entering custody, Have symptoms<br>indicative
           of<br>psychosis, Identified as<br>suffering from<br>both anxiety
           and<br>depression, Have ever used<br>Class A drug, Drank alcohol<br>every
           day in the<br>four weeks before<br>custody]
 }),
 Scatter({
     'hovertemplate': '%{x}',
     'marker': {'color': '#FFA15A'},
     'name': 'general_pop',
     'orientation': 'h',
     'text': [general_pop, general_pop, general_pop, general_pop, general_pop,
              general_pop, general_pop, general_pop, general_pop, general_pop,
              general_pop, general_pop, general_pop, general_pop, general_pop,
              general_pop],
     'textposition': 'top center',
     'texttemplate': '%{text}%',
     'x': [2, 20, 14, 5, <1, 15, 7.7, 3.9, 4, 27, 4, 4, 15, 6, 13, 16],
     'y': [Taken into care as<br>a child, Experienced abuse<br>as a child, Observed
           violence<br>in the home as a<br>child, Regularly truant<br>from school,
           Expelled or<br>permanently<br>excluded from<br>school, No qualifications,
           Unemployed in the<br>four weeks before<br>custody, Never had a job,
           Homeless before<br>entering custody, Have children<br>under the age
           of<br>18, Are young fathers<br>(aged 18-20), Have symptoms<br>indicative
           of<br>psychosis, Identified as<br>suffering from<br>both anxiety
           and<br>depression, Have attempted<br>suicide at some<br>point, Have ever
           used<br>Class A drug, Drank alcohol<br>every day in the<br>four weeks
           before<br>custody]
 })]

In [65]:
fig = plotly_social_characteristics.main()
fig

In [52]:
df = plotly_social_characteristics.test_data()
df

,characteristic,group,value,wrapped_characteristic
0,Taken into care as a child,General population,2,Taken into care as a child
1,Experienced abuse as a child,General population,20,Experienced abuse as a child
2,Observed violence in the home as a child,General population,14,Observed violence in the<br>home as a child
3,Regularly truant from school,General population,5,Regularly truant from school
4,Expelled or permanently excluded from school,General population,<1,Expelled or permanently<br>excluded from school
5,No qualifications,General population,15,No qualifications
6,Unemployed in the four weeks before custody,General population,7.7,Unemployed in the four weeks<br>before custody
7,Never had a job,General population,3.9,Never had a job
8,Homeless before entering custody,General population,4,Homeless before entering<br>custody
9,Have children under the age of 18,General population,27,Have children under the age<br>of 18
10,Are young fathers (aged 18-20),General population,4,Are young fathers (aged<br>18-20)
11,Have symptoms indicative of psychosis,General population,4,Have symptoms indicative of<br>psychosis
12,Identified as suffering from both anxiety and ...,General population,15,Identified as suffering from<br>both anxiety a...
13,Have attempted suicide at some point,General population,6,Have attempted suicide at<br>some point
14,Have ever used Class A drug,General population,13,Have ever used Class A drug
15,Drank alcohol every day in the four weeks befo...,General population,16,Drank alcohol every day in<br>the four weeks b...
16,Taken into care as a child,Men in prison,24.0,Taken into care as a child
17,Experienced abuse as a child,Men in prison,27.0,Experienced abuse as a child
18,Observed violence in the home as a child,Men in prison,40.0,Observed violence in the<br>home as a child
19,Expelled or permanently excluded from school,Men in prison,43.0,Expelled or permanently<br>excluded from school
20,Unemployed in the four weeks before custody,Men in prison,67.0,Unemployed in the four weeks<br>before custody
21,Have children under the age of 18,Men in prison,45.0,Have children under the age<br>of 18
22,Are young fathers (aged 18-20),Men in prison,19.0,Are young fathers (aged<br>18-20)
23,Have symptoms indicative of psychosis,Men in prison,15.0,Have symptoms indicative of<br>psychosis
24,Identified as suffering from both anxiety and ...,Men in prison,23.0,Identified as suffering from<br>both anxiety a...
25,Have attempted suicide at some point,Men in prison,21.0,Have attempted suicide at<br>some point
26,Taken into care as a child,Women in prison,31.0,Taken into care as a child
27,Experienced abuse as a child,Women in prison,53.0,Experienced abuse as a child
28,Observed violence in the home as a child,Women in prison,50.0,Observed violence in the<br>home as a child
29,Expelled or permanently excluded from school,Women in prison,32.0,Expelled or permanently<br>excluded from school
30,Unemployed in the four weeks before custody,Women in prison,81.0,Unemployed in the four weeks<br>before custody
31,Have children under the age of 18,Women in prison,47.0,Have children under the age<br>of 18
32,Have symptoms indicative of psychosis,Women in prison,25.0,Have symptoms indicative of<br>psychosis
33,Identified as suffering from both anxiety and ...,Women in prison,49.0,Identified as suffering from<br>both anxiety a...
34,Have attempted suicide at some point,Women in prison,46.0,Have attempted suicide at<br>some point
35,Experienced abuse as a child,Prison population (overall),29.0,Experienced abuse as a child
36,Observed violence in the home as a child,Prison population (overall),41.0,Observed violence in the<br>home as a child
37,Regularly truant from school,Prison population (overall),59.0,Regularly truant from school
38,Expelled or permanently excluded from school,Prison population (overall),42.0,Expelled or permanently<br>excluded from school
39,No qualifications,Prison population (overall),47.0,No qualifications
40,Unemployed in the four weeks before custody,Prison population (overall),68.0,Unemployed in the four weeks<br>before custody
41,Never had a job,Prison population (overall),13.0,Never had a job
42,Homeless before entering custody,Prison population (overall),15.0,Homeless before entering<br>custody
43,Have symptoms indicative of psychosis,Prison population (overall),16.0,Have symptoms indicative of<br>psychosis
44,Identified as suffering from both anxiety and ...,Prison population (overall),25.0,Identified as suffering from<br>both anxiety a...
45,Have ever used Class A drug,Prison population (overall),64.0,Have ever used Class A drug
46,Drank alcohol every day in the four weeks befo...,Prison population (overall),22.0,Drank alcohol every day in<br>the four weeks b...

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   characteristic          47 non-null     category
 1   group                   47 non-null     category
 2   value                   47 non-null     object
 3   wrapped_characteristic  47 non-null     category
dtypes: category(3), object(1)
memory usage: 2.2+ KB