# Development and testing for sentence explainer charts

## Script test

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.visualization.sentences_explained import sentences_explained_legend

In [75]:
df = (
    sentences_explained_legend
    .load_data()
    .pipe(sentences_explained_legend.prepare_data)
    )
df

0          sentence value                                               text
0         suspended    20                                 suspended sentence
1         custodial    20                       custodial period of sentence
2       licence_dis    20  Part of custodial period spent on licence foll...
3      licence_auto    20  Part of custodial period spent on licence foll...
4  extended_licence    20                            Extended licence period

In [78]:
[(i, sentence) for i, sentence in enumerate(df['sentence'])]

[(0, 'suspended'),
 (1, 'custodial'),
 (2, 'licence_dis'),
 (3, 'licence_auto'),
 (4, 'extended_licence')]

In [100]:
sentences_explained_legend.generate_traces(df)

[Bar({
     'hovertemplate': '%{text}<extra></extra>',
     'insidetextanchor': 'middle',
     'marker': {'color': '#F9A237'},
     'orientation': 'h',
     'text': 'Suspended sentence',
     'textfont': {'color': 'white'},
     'textposition': 'inside',
     'x': [20],
     'y': [1]
 }),
 Bar({
     'hovertemplate': '%{text}<extra></extra>',
     'insidetextanchor': 'middle',
     'marker': {'color': '#A01D28'},
     'orientation': 'h',
     'text': 'Custodial period of<br>sentence',
     'textfont': {'color': 'white'},
     'textposition': 'inside',
     'x': [20],
     'y': [1]
 }),
 Bar({
     'hovertemplate': '%{text}<extra></extra>',
     'insidetextanchor': 'middle',
     'marker': {'color': '#808080'},
     'orientation': 'h',
     'text': ('Part of custodial period<br>sp' ... 'owing discretionary<br>release'),
     'textfont': {'color': 'white'},
     'textposition': 'inside',
     'x': [20],
     'y': [1]
 }),
 Bar({
     'hovertemplate': '%{text}<extra></extra>',
     'insidetextanchor': 'middle',
     'marker': {'color': '#499CC9'},
     'orientation': 'h',
     'text': 'Part of custodial period<br>spent on licence<br>following automatic<br>release',
     'textfont': {'color': 'white'},
     'textposition': 'inside',
     'x': [20],
     'y': [1]
 }),
 Bar({
     'hovertemplate': '%{text}<extra></extra>',
     'insidetextanchor': 'middle',
     'marker': {'color': '#573D6B'},
     'orientation': 'h',
     'text': 'Extended licence period',
     'textfont': {'color': 'white'},
     'textposition': 'inside',
     'x': [20],
     'y': [1]
 })]

In [104]:
fig = sentences_explained_legend.prepare_chart()
fig

## Data manipulation

In [1]:
import pandas as pd

In [2]:
# Read in datasets 
levy = pd.read_csv("data/processed/rehabilitation_and_resettlement/victims_levy.csv")
levy

       year  value
0   2011-12    0.4
1      2013    0.8
2      2014    1.0
3      2015    1.1
4      2016    1.0
5      2017    1.1
6      2018    1.4
7      2019    1.6
8      2020    2.2
9      2021    0.9
10     2022    2.0
11     2023    3.5
12     2024    4.2
13     2025    3.9

In [3]:
levy['value'].cumsum()

0      0.4
1      1.2
2      2.2
3      3.3
4      4.3
5      5.4
6      6.8
7      8.4
8     10.6
9     11.5
10    13.5
11    17.0
12    21.2
13    25.1
Name: value, dtype: float64

In [4]:
# Calculating running_total of annual levy
levy['running_total'] = levy['value'].cumsum()
levy['bottom'] = levy['value'].cumsum().shift(fill_value=0)

In [5]:
levy

       year  value  running_total  bottom
0   2011-12    0.4            0.4     0.0
1      2013    0.8            1.2     0.4
2      2014    1.0            2.2     1.2
3      2015    1.1            3.3     2.2
4      2016    1.0            4.3     3.3
5      2017    1.1            5.4     4.3
6      2018    1.4            6.8     5.4
7      2019    1.6            8.4     6.8
8      2020    2.2           10.6     8.4
9      2021    0.9           11.5    10.6
10     2022    2.0           13.5    11.5
11     2023    3.5           17.0    13.5
12     2024    4.2           21.2    17.0
13     2025    3.9           25.1    21.2